services:
  chatbot-api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chatbot-api
    restart: always

