services:
  chatbot-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    image: chatbot-api:latest
    container_name: chatbot-api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chatbot-api
    restart: always
    container_name: chatbot-nginx

