service: rag-chatbot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'ap-northeast-2'}
  timeout: 300  # 5분 (최대 Lambda 시간)
  memorySize: 2048  # 2GB (임베딩 처리에 충분한 메모리)
  logRetentionInDays: 14  # 로그 그룹 보존 기간 (14일)
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION, 'ap-northeast-2'}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    LAMBDA_ENVIRONMENT: 'true'  # Lambda 환경임을 표시
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::${env:S3_BUCKET_NAME}"
            - "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  chatApi:
    handler: lambda_function.lambda_handler
    description: "RAG 챗봇 API - PDF 문서에 기반한 질의응답 시스템"
    events:
      - http:
          path: /chat
          method: post
          cors: true
      - http:
          path: /chat/reset
          method: post
          cors: true
    # 콜드 스타트 최소화를 위한 웜 인스턴스 유지
    provisionedConcurrency: 1

package:
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!.env'
    - '!.git/**'
    - '!tests/**'
    - '!.gitignore'
    - '!README.md'
    - '!Dockerfile'
    - '!docker-compose.yml'
    - '!nginx/**'
    - '!**/__pycache__/**'
    - '!*.pyc'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements-lambda.txt
    zip: true
    slim: true
    useDownloadCache: true
    useStaticCache: true 